
CREATE TABLE TEST.ITEM
(
    ID          BIGINT,
    SKU         VARCHAR(50),
    ITEM_NAME   VARCHAR(200),
    STOCK_QUANTITY  BIGINT,
    CATEGORY1   INTEGER,
    CATEGORY2   INTEGER,
    SUPPLIER    VARCHAR(200),
    WAREHOUSE   VARCHAR(200),
    CONSTRAINT PK_ITEM PRIMARY KEY(ID)
);